### PR TITLE
Week 4's Work

### PR DESCRIPTION
**Pull request by mmarchetti2**
I added the code necessary to make the program work. It now works
perfectly fine from the runner file. :)

### CODE REVIEW

**Comment by mmarchetti2** [comment]
Hm... For some reason it's not letting me win diagonally or vertically, do you know the solution to this?

**Comment by halfaro1** [comment]
@mmarchetti2 I know the solution, but me telling it to you is no fun :) I'd like you to figure it out and I'm happy to help. I'd recommend walking through your if-statements and determining their outcomes.

**Comment by mmarchetti2** [comment]
Okay, there we go. I think I've solved the problem. I'm not quite sure why the checks have failed, it seemed like it worked when I tried it.

**Comment by halfaro1** [comment]
@mmarchetti2 ok, walk me through your logic for the if-statements. Tell me, in words, how you expect it to work and the behavior you're seeing actually occur?

**Comment by mmarchetti2** [comment]
Okay, well I'd expect it to check each of the statements, and if one of them is correct, I would think it would return True, and not False. If all of them are incorrect, it should return False. I'm not really seeing any error when I try to use the program, but that may be because I haven't tried every single combination. As far as I've tested, it works winning diagonally, horizontally, and vertically for both X and O.

**Comment by mmarchetti2** [comment]
Hm... Okay, well I changed the if statements to elif statements and that didn't seem to work either. Was the setup of the if statements okay, or is it the actual code within the if statements that needs working on?

**Comment by halfaro1** [comment]
@mmarchetti2 the way it's currently set up, the `elif` statements are dependent on the `if` statements. For example, line 25 only runs if line if line 21 and line 17 aren't true. You may want to think about streamlining this a bit, I can help if you need it.

**Comment by mmarchetti2** [comment]
Okay, so I see what you mean, but I'm not quite sure how to fix it. When I first typed it up, I thought it might be a bit too much, and that there could be a simpler way to do this. But if you could help, that would be great! I'm somewhat clueless as to how to get around the problem, so any advice you could give me would really help me.

**Comment by halfaro1** [comment]
@mmarchetti2 alright I'll take a stab at explaining it in writing but if you'd like to set up a call it might be easier to explain. Try having 8 independent `if` statements -- that means that they'll each run their tests. You don't want to get into the situation where the top-left box is an 'X', for example, and when the box adjacent to it is an 'O', your tests stop running (which is what's currently happening). If you set up 8 independent test, each of those 8 will run regardless of the outcome of a previous match (unless there's a `return` statement. So I'll write it in pseudocode below:
```
if top-L == player:
  if mid-L == player:
    if low-L == player:
      return True
if top-M == player:
  if mid-M == player:
    if low-M == player:
      returnTrue
#... and so on
```
Something else you could do to save a little space (but not required) is try combining some of these tests using logic, like this:
```
if top-L == player and mid-L == player and low-L == player:
  return True
```

**Comment by mmarchetti2** [comment]
Okay, there we go! All fixed, and it passed the checks! Thank you so much for helping me! :D

**Comment by halfaro1** [comment]
Wohoo! Very happy for you, @mmarchetti2.

**Pull request closed without merging**
