### PR TITLE
week 4

### PR DESCRIPTION
**Pull request by alalta**

### CODE REVIEW

**Comment by halfaro1** [comment]
@alalta it looks like your print function works well. How about the `checkWinner` function, though? You may want to add more code to that function so it performs the checks being asked for.

**Comment by alalta** [comment]
That's what I was confused on. I don't know what function I should use to get the winner. Is it somewhere in chapter 4 or 5?
________________________________

**Comment by halfaro1** [comment]
@alalta those chapters will help, yes.

**Comment by alalta** [comment]
is there anyway you can tell me where exactly in those chapters to find it? I cant seem to figure it out.


________________________________

**Comment by halfaro1** [comment]
@alalta let's try to narrow down what you're trying to do. No one chapter is going to walk you through the whole project, but if there's one thing that's holding you back I can point you to the part of the book that covers that.

**Comment by halfaro1** [comment]
@alalta 
Thanks for continuing to work on this project! Unfortunately, I have to grade this project as-is. I am closing out this pull request and entering your grade on Blackboard. Please see your grade there.

**Pull request closed without merging**
