### PR TITLE
week 4

### PR DESCRIPTION
**Pull request by haleyhager**

### CODE REVIEW

**Comment by halfaro1** [comment]
@haleyhager you're almost there! check your indentation starting around line 19.

**Comment by haleyhager** [comment]
I fixed the indenting but now when I run it it already checks for the winner before fully playing the game. Not sure how to go about fixing that.

**Comment by haleyhager** [comment]
@ngocnguyen83 you mean as in, replacing all of the 'X' and 'O' with 'player' instead?

**Comment by halfaro1** [comment]
@haleyhager yes, I think @ngocnguyen83 hit the nail on the head - follow her advice!

**Comment by haleyhager** [comment]
Okay, when I have 'player' in place, it ends up never actually checking for the winner. When it's the 'X' and 'O', it checks for the winner from the start. Any hints or suggestions? @halfaro1 @ngocnguyen83

**Comment by halfaro1** [comment]
@haleyhager the fact that `'player'` is in quotes, it is checking if the winner is equal to the string `'player'`. You'd like to check if the winner is equal to the *variable* `player`, so try taking out the quotes.

**Comment by haleyhager** [comment]
@halfaro1 thank you so much, it worked. Ran it and had no issues.

**Comment by halfaro1** [comment]
@haleyhager great, one more thing! did you start to work on a different file? the automated tests didn't run because it says your code is in an executable file

**Comment by halfaro1** [comment]
@haleyhager please let me know if you have any questions about this project

**Pull request closed without merging**
