### PR TITLE
Update ticTacToe.py

### PR DESCRIPTION
**Pull request by kristinabeck**

### CODE REVIEW

**Comment by halfaro1** [comment]
@kristinabeck great start. The references to the dictionary in lines 12-27 should be in single quotes. For example: `board['top-L']` instead of `board[top-L]`

**Comment by kristinabeck** [comment]
Will I be getting any points or credit for this? I still have 0/10

**Comment by halfaro1** [comment]
@kristinabeck will you correct it? or do you want me to grade it as is?

**Comment by kristinabeck** [comment]
Oh! l will try and make the corrections


Thanks!

Kristina Beck


________________________________

**Comment by halfaro1** [comment]
@kristinabeck let me know if you need some help. I'm glad to lend a hand where you need it.

**Comment by halfaro1** [comment]
@kristinabeck 
Thanks for continuing to work on this project! Unfortunately, I have to grade this project as-is. I am closing out this pull request and entering your grade on Blackboard. Please see your grade there.

**Pull request closed without merging**
